version: "3"
services:

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  backend:
    container_name: scrappy-api
    build:
      context: .
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - redis

volumes:
  backend:
  redis: