version: "3"
services:

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  app:
    container_name: nodeapp-container
    image: node:18
    working_dir: ${PWD}
    command: bash -c "npm i && npm run start"
    restart: always
    ports: 
      - "3000:3000"
      - ./build/:${PWD}/build/
      - ./package.json:${PWD}/package.json

  volumes:
    redis: